/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package starfire.terra.model


case class NewMethodConfigIngest (
  // Method configuration namespace
  namespace: String,
  // Method configuration name
  name: String,
  // Method configuration root entity type
  rootEntityType: String,
  // Input map - Map[string, string]
  inputs: Any,
  // Output map - Map[string, string]
  outputs: Any,
  // Prerequisites map - Map[string, string]
  prerequisites: Any,
  // Method ID - Map
  methodRepoMethod: Any,
  // Version number, incremented on edit
  methodConfigVersion: Integer,
  // Is this config marked as deleted?
  deleted: Boolean
)

