/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package starfire.terra.model


case class ResearchPurposeRequest (
  // Disease focused research. Values are DOID ontology node ids in the form http://purl.obolibrary.org/obo/DOID_NNN. Specify an empty array if this is not disease focused research. 
  DS: Option[List[String]] = None,
  // Methods development/Validation study
  NMDS: Option[Boolean] = None,
  // Control set
  NCTRL: Option[Boolean] = None,
  // Aggregate analysis to understand variation in the general population
  NAGR: Option[Boolean] = None,
  // Study population origins or ancestry
  POA: Option[Boolean] = None,
  // Commercial purpose/by a commercial entity
  NCU: Option[Boolean] = None,
  // Prefix for query properties. Must match prefix used when indexing.
  prefix: Option[String] = None
)

