/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package starfire.terra.model


case class SubmissionsCountResponse (
  accepted: Option[Integer] = None,
  evaluating: Option[Integer] = None,
  submitting: Option[Integer] = None,
  submitted: Option[Integer] = None,
  aborting: Option[Integer] = None,
  aborted: Option[Integer] = None,
  done: Option[Integer] = None
)

