/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package starfire.terra.model


case class ToolInputParameter (
  // The name of this input value (formatted as expected by the tool)
  name: String,
  valueType: ValueType,
  // Whether the tool allows this value to not be specified
  optional: Boolean,
  // The in-language expression used to evaluate a default value for this parameter, if none is supplied.
  default: String
)

