/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package starfire.terra.model


case class UserImportPermission (
  // does the user have at least one ready billing project?
  billingProject: Option[Boolean] = None,
  // does the user have at least one writable workspace?
  writableWorkspace: Option[Boolean] = None
)

