/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package starfire.terra.model

import java.util.Date

case class Workflow (
  // Workflow unique identifier
  workflowId: Option[String] = None,
  // Workflow status
  status: Option[WorkflowStatus] = None,
  // Status last-changed date
  statusLastChangedDate: Option[Date] = None,
  // Optional if this workflow did not run on an entity (i.e. its method configuration has no root entity)
  workflowEntity: Option[AttributeEntityReference] = None,
  // The evaluation of each input
  inputResolutions: Option[List[SubmissionValidationValue]] = None,
  // List of messages about this workflow
  messages: Option[List[String]] = None,
  // The run cost of this workflow
  cost: Option[Float] = None
)

