/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.broadinstitute.starfire.model

import org.broadinstitute.starfire.Decoders._
import org.broadinstitute.starfire.Encoders._
import io.circe.generic.JsonCodec

@JsonCodec case class MethodConfigRename (
  // Method configuration namespace
  namespace: String,
  // Method configuration name
  name: String,
  // Map[String, String] with corresponding workspace-related information - name and namespace
  workspaceName: Map[String, String]
)

