/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.broadinstitute.starfire.model

import io.swagger.sttp.utils.Decoders._
import io.swagger.sttp.utils.Encoders._
import io.circe.generic.JsonCodec

@JsonCodec case class ResearchPurpose (
  // Disease focused research. Values are DOID ontology node ids in the form http://purl.obolibrary.org/obo/DOID_NNN. Specify an empty array if this is not disease focused research. 
  DS: List[String],
  // Methods development/Validation study
  NMDS: Boolean,
  // Control set
  NCTRL: Boolean,
  // Aggregate analysis to understand variation in the general population
  NAGR: Boolean,
  // Study population origins or ancestry
  POA: Boolean,
  // Commercial purpose/by a commercial entity
  NCU: Boolean
)

