/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.broadinstitute.starfire.model

import io.circe.Json
import io.circe.Json._
import io.swagger.sttp.utils.Decoders._
import io.swagger.sttp.utils.Encoders._
import io.circe.generic.JsonCodec

@JsonCodec case class ValidatedMethodConfiguration (
  validInputs: List[String],
  invalidInputs: Map[String, Json],
  missingInputs: List[String],
  extraInputs: List[String],
  validOutputs: List[String],
  invalidOutputs: Map[String, Json],
  methodConfiguration: MethodConfiguration
)

