/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.broadinstitute.starfire.model

import io.swagger.sttp.utils.Decoders._
import io.swagger.sttp.utils.Encoders._
import io.circe.generic.JsonCodec

@JsonCodec case class WorkflowDescription (
  // Whether the workflow and inputs as submitted passed validation
  valid: Boolean,
  // The set of validation failure messages
  errors: List[String],
  // For a source file with one workflow and zero or more tasks, the name of the workflow. For a single task, the name of the task. For a source file with multiple tasks but no workflows, the empty string.
  name: String,
  // A list of inputs for this tool
  inputs: List[ToolInputParameter],
  // A list of outputs for this tool
  outputs: List[ToolOutputParameter],
  submittedDescriptorType: DescriptorTypeAndVersion
)

