/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.broadinstitute.starfire.model

import org.broadinstitute.starfire.Decoders._
import org.broadinstitute.starfire.Encoders._
import io.circe.generic.JsonCodec

@JsonCodec case class WorkspaceACLUpdateResponse (
  // id of the user or group whose permissions will be changed
  subjectId: String,
  // The access level granted to this user or group (OWNER, READER, WRITER, NO ACCESS)
  accessLevel: String
)

