/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.broadinstitute.starfire.api

import org.broadinstitute.starfire.model.JWTWrapper
import org.broadinstitute.starfire.model.JWTWrapper._
import org.broadinstitute.starfire.model.NihStatus
import org.broadinstitute.starfire.model.NihStatus._

import sttp.client._
import sttp.client.circe._
import io.circe.generic.auto._

import io.swagger.sttp.utils.Decoders._
import io.swagger.sttp.utils.Encoders._
import io.swagger.sttp.utils.SttpUtils.Implicits._

object NIHApi {

  /**
   * Updates a user&#39;s NIH link from a JWT
   * 
   *
   * @param jwt JWT from NIH login 
   * @return Option[NihStatus]
   */
  def nIHCallback(
    jwt: JWTWrapper): Request[Either[ResponseError[io.circe.Error],NihStatus],Nothing] = {
    assert(jwt != null, "Missing required parameter 'jwt' when calling NIHApi->nIHCallback")

    basicRequest
      .post(uri"https://api.firecloud.org/api/nih/callback")
      .body(jwt)
      .response(asJson[NihStatus])
  }

  /**
   * Retrieves info about a user&#39;s NIH link
   * 
   *
   * @return Option[NihStatus]
   */
  def nIHStatus(
    ): Request[Either[ResponseError[io.circe.Error],NihStatus],Nothing] = {

    basicRequest
      .get(uri"https://api.firecloud.org/api/nih/status")
      .response(asJson[NihStatus])
  }

}

