/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.broadinstitute.starfire.api

import org.broadinstitute.starfire.model.Body1
import org.broadinstitute.starfire.model.Body1._
import io.circe.Json
import io.circe.Json._

import sttp.client._
import sttp.client.circe._
import io.circe.generic.auto._

import org.broadinstitute.starfire.Decoders._
import org.broadinstitute.starfire.Encoders._
import org.broadinstitute.starfire.SttpUtils.Implicits._

class OAuthApi() {

  /**
   * deprecated
   * This API is a deprecated noop. Previously, it returned the status of the current user&#39;s refresh token. Since refresh tokens are no longer used in the back end, this API is now hardcoded to respond as if the user&#39;s refresh token is valid. This API may be removed in a future release. 
   *
   * @return Option[Json]
   */
  def getRefreshTokenStatus(
    ): Request[Either[ResponseError[io.circe.Error],Json],Nothing] = {

    basicRequest
      .get(uri"https://localhost/api/refresh-token-status")
      .response(asJson[Json])
  }

  /**
   * deprecated
   * This API is a deprecated noop. Previously, it allowed the server to acquire a refresh token. Since refresh tokens are no longer used in the back end, this API is now hardcoded to respond as if it successfully acquired a refresh token, without doing any actual work. This API may be removed in a future release. 
   *
   * @param body  (optional)
   * @return Option[Unit]
   */
  def handleOauthCode(
    body: Option[Body1] = None
    ): Request[Either[ResponseError[io.circe.Error],Unit],Nothing] = {

    basicRequest
      .post(uri"https://localhost/handle-oauth-code")
      .body(body)
      .response(asJson[Unit])
  }

}

