/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.broadinstitute.starfire.api


import sttp.client._
import sttp.client.circe._
import io.circe.generic.auto._

import io.swagger.sttp.utils.Decoders._
import io.swagger.sttp.utils.Encoders._
import io.swagger.sttp.utils.SttpUtils.Implicits._

object StaticNotebooksApi {

  /**
   * Convert a Notebook ipynb file to a static HTML representation 
   * Convert a Notebook ipynb file to a static HTML representation 
   *
   * @param notebook Notebook ipynb file 
   * @return Option[io.circe.Json]
   */
  def convertNotebook(
    notebook: String): Request[Either[ResponseError[io.circe.Error],io.circe.Json],Nothing] = {
    assert(notebook != null, "Missing required parameter 'notebook' when calling StaticNotebooksApi->convertNotebook")

    basicRequest
      .post(uri"https://api.firecloud.org/api/staticNotebooks/convert")
      .body(notebook)
      .response(asJson[io.circe.Json])
  }

}

