/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.broadinstitute.starfire.api

import org.broadinstitute.starfire.model.SystemStatus
import org.broadinstitute.starfire.model.SystemStatus._

import sttp.client._
import sttp.client.circe._
import io.circe.generic.auto._

import org.broadinstitute.starfire.Decoders._
import org.broadinstitute.starfire.Encoders._
import org.broadinstitute.starfire.SttpUtils.Implicits._

class StatusApi() {

  /**
   * An error status endpoint for load balancing purposes 
   * 
   *
   * @return Option[Unit]
   */
  def error(
    ): Request[Either[ResponseError[io.circe.Error],Unit],Nothing] = {

    basicRequest
      .get(uri"https://localhost/error")
      .response(asJson[Unit])
  }

  /**
   * A health status endpoint for load balancing purposes 
   * 
   *
   * @return Option[Unit]
   */
  def health(
    ): Request[Either[ResponseError[io.circe.Error],Unit],Nothing] = {

    basicRequest
      .get(uri"https://localhost/health")
      .response(asJson[Unit])
  }

  /**
   * An orchestrated status check that includes a health report of underlying systems 
   * 
   *
   * @return Option[SystemStatus]
   */
  def status(
    ): Request[Either[ResponseError[io.circe.Error],SystemStatus],Nothing] = {

    basicRequest
      .get(uri"https://localhost/status")
      .response(asJson[SystemStatus])
  }

}

