/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package starfire.terra.api

import java.text.SimpleDateFormat

import starfire.terra.model.NotificationType
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class NotificationsApi(
  val defBasePath: String = "https://localhost",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new NotificationsApiAsyncHelper(client, config)

  /**
   * Gets the general notifications available
   * 
   *
   * @return List[NotificationType]
   */
  def generalNotifications(): Option[List[NotificationType]] = {
    val await = Try(Await.result(generalNotificationsAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Gets the general notifications available asynchronously
   * 
   *
   * @return Future(List[NotificationType])
   */
  def generalNotificationsAsync(): Future[List[NotificationType]] = {
      helper.generalNotifications()
  }

  /**
   * Gets the notifications available for a workspace
   * 
   *
   * @param workspaceNamespace workspace namespace 
   * @param workspaceName workspace name 
   * @return List[NotificationType]
   */
  def workspaceNotifications(workspaceNamespace: String, workspaceName: String): Option[List[NotificationType]] = {
    val await = Try(Await.result(workspaceNotificationsAsync(workspaceNamespace, workspaceName), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Gets the notifications available for a workspace asynchronously
   * 
   *
   * @param workspaceNamespace workspace namespace 
   * @param workspaceName workspace name 
   * @return Future(List[NotificationType])
   */
  def workspaceNotificationsAsync(workspaceNamespace: String, workspaceName: String): Future[List[NotificationType]] = {
      helper.workspaceNotifications(workspaceNamespace, workspaceName)
  }

}

class NotificationsApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def generalNotifications()(implicit reader: ClientResponseReader[List[NotificationType]]): Future[List[NotificationType]] = {
    // create path and map variables
    val path = (addFmt("/api/notifications/general"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def workspaceNotifications(workspaceNamespace: String,
    workspaceName: String)(implicit reader: ClientResponseReader[List[NotificationType]]): Future[List[NotificationType]] = {
    // create path and map variables
    val path = (addFmt("/api/notifications/workspace/{workspaceNamespace}/{workspaceName}")
      replaceAll("\\{" + "workspaceNamespace" + "\\}", workspaceNamespace.toString)
      replaceAll("\\{" + "workspaceName" + "\\}", workspaceName.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (workspaceNamespace == null) throw new Exception("Missing required parameter 'workspaceNamespace' when calling NotificationsApi->workspaceNotifications")

    if (workspaceName == null) throw new Exception("Missing required parameter 'workspaceName' when calling NotificationsApi->workspaceNotifications")


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
