/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package starfire.terra.api

import java.text.SimpleDateFormat

import starfire.terra.model.Body1
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class OAuthApi(
  val defBasePath: String = "https://localhost",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new OAuthApiAsyncHelper(client, config)

  /**
   * deprecated
   * This API is a deprecated noop. Previously, it returned the status of the current user&#39;s refresh token. Since refresh tokens are no longer used in the back end, this API is now hardcoded to respond as if the user&#39;s refresh token is valid. This API may be removed in a future release. 
   *
   * @return Any
   */
  def getRefreshTokenStatus(): Option[Any] = {
    val await = Try(Await.result(getRefreshTokenStatusAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * deprecated asynchronously
   * This API is a deprecated noop. Previously, it returned the status of the current user&#39;s refresh token. Since refresh tokens are no longer used in the back end, this API is now hardcoded to respond as if the user&#39;s refresh token is valid. This API may be removed in a future release. 
   *
   * @return Future(Any)
   */
  def getRefreshTokenStatusAsync(): Future[Any] = {
      helper.getRefreshTokenStatus()
  }

  /**
   * deprecated
   * This API is a deprecated noop. Previously, it allowed the server to acquire a refresh token. Since refresh tokens are no longer used in the back end, this API is now hardcoded to respond as if it successfully acquired a refresh token, without doing any actual work. This API may be removed in a future release. 
   *
   * @param body  (optional)
   * @return void
   */
  def handleOauthCode(body: Option[Body1] = None) = {
    val await = Try(Await.result(handleOauthCodeAsync(body), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * deprecated asynchronously
   * This API is a deprecated noop. Previously, it allowed the server to acquire a refresh token. Since refresh tokens are no longer used in the back end, this API is now hardcoded to respond as if it successfully acquired a refresh token, without doing any actual work. This API may be removed in a future release. 
   *
   * @param body  (optional)
   * @return Future(void)
   */
  def handleOauthCodeAsync(body: Option[Body1] = None) = {
      helper.handleOauthCode(body)
  }

}

class OAuthApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def getRefreshTokenStatus()(implicit reader: ClientResponseReader[Any]): Future[Any] = {
    // create path and map variables
    val path = (addFmt("/api/refresh-token-status"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def handleOauthCode(body: Option[Body1] = None
    )(implicit reader: ClientResponseReader[Unit], writer: RequestWriter[Option[Body1]]): Future[Unit] = {
    // create path and map variables
    val path = (addFmt("/handle-oauth-code"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(body))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
