/**
 * FireCloud
 * Genome analysis execution service. 
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package starfire.terra.api

import java.text.SimpleDateFormat

import java.io.File
import starfire.terra.model.WorkflowDescription
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class WomtoolApi(
  val defBasePath: String = "https://localhost",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new WomtoolApiAsyncHelper(client, config)

  /**
   * Machine-readable description of a workflow, including inputs and outputs
   * 
   *
   * @param version Cromwell API Version 
   * @param workflowSource The workflow source file to submit for execution. Either workflow source or workflow url is required. (optional)
   * @param workflowUrl URL which points to the workflow. Either workflow source or workflow url is required. (optional)
   * @param workflowInputs JSON or YAML file containing the inputs as an object. (optional)
   * @param workflowType The workflow language for the file you submitted. Cromwell currently supports WDL and CWL. (optional)
   * @param workflowTypeVersion The specification version for the workflow language being used. For WDL, Cromwell currently supports draft-2 and 1.0. For CWL, Cromwell currently supports v1.0. (optional)
   * @return WorkflowDescription
   */
  def describe(version: String, workflowSource: Option[File] = None, workflowUrl: Option[String] = None, workflowInputs: Option[File] = None, workflowType: Option[String] = None, workflowTypeVersion: Option[String] = None): Option[WorkflowDescription] = {
    val await = Try(Await.result(describeAsync(version, workflowSource, workflowUrl, workflowInputs, workflowType, workflowTypeVersion), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Machine-readable description of a workflow, including inputs and outputs asynchronously
   * 
   *
   * @param version Cromwell API Version 
   * @param workflowSource The workflow source file to submit for execution. Either workflow source or workflow url is required. (optional)
   * @param workflowUrl URL which points to the workflow. Either workflow source or workflow url is required. (optional)
   * @param workflowInputs JSON or YAML file containing the inputs as an object. (optional)
   * @param workflowType The workflow language for the file you submitted. Cromwell currently supports WDL and CWL. (optional)
   * @param workflowTypeVersion The specification version for the workflow language being used. For WDL, Cromwell currently supports draft-2 and 1.0. For CWL, Cromwell currently supports v1.0. (optional)
   * @return Future(WorkflowDescription)
   */
  def describeAsync(version: String, workflowSource: Option[File] = None, workflowUrl: Option[String] = None, workflowInputs: Option[File] = None, workflowType: Option[String] = None, workflowTypeVersion: Option[String] = None): Future[WorkflowDescription] = {
      helper.describe(version, workflowSource, workflowUrl, workflowInputs, workflowType, workflowTypeVersion)
  }

}

class WomtoolApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def describe(version: String,
    workflowSource: Option[File] = None,
    workflowUrl: Option[String] = None,
    workflowInputs: Option[File] = None,
    workflowType: Option[String] = None,
    workflowTypeVersion: Option[String] = None
    )(implicit reader: ClientResponseReader[WorkflowDescription]): Future[WorkflowDescription] = {
    // create path and map variables
    val path = (addFmt("/api/womtool/{version}/describe")
      replaceAll("\\{" + "version" + "\\}", version.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (version == null) throw new Exception("Missing required parameter 'version' when calling WomtoolApi->describe")


    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
